# Generated by Django 2.1.3 on 2018-11-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='hoge', max_length=100, unique=True, verbose_name='ユーザ名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='hoge@fuga.com', max_length=255),
        ),
    ]
