# Generated by Django 2.1.3 on 2018-11-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='太郎', max_length=50, verbose_name='名'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='工繊', max_length=50, verbose_name='姓'),
        ),
    ]
