# Generated by Django 2.1.3 on 2018-11-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='demoalarm',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='demoalarm',
            name='updated_at',
        ),
    ]
