# Generated by Django 2.1.3 on 2018-11-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('lat', models.FloatField(verbose_name='緯度')),
                ('lon', models.FloatField(verbose_name='経度')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='shelter',
            unique_together={('lat', 'lon')},
        ),
    ]
