# Generated by Django 2.1.3 on 2018-11-06 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evacuation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='避難している人数')),
                ('created_at', models.DateTimeField(verbose_name='取得日')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='evacuation.Shelter', verbose_name='避難所')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalEvacuationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_evacuated', models.BooleanField(verbose_name='避難しているか')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_histories', to='evacuation.Shelter', verbose_name='避難所')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_histories', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
