# Generated by Django 2.1.3 on 2018-11-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0002_evacuationhistory_personalevacuationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalevacuationhistory',
            name='created_at',
            field=models.DateTimeField(verbose_name='日付'),
        ),
    ]
