# Generated by Django 2.1.3 on 2018-11-06 07:58

import random
from django.db import migrations


def set_random_capacity(apps, scheme_editor):
    Shelter = apps.get_model('evacuation', 'Shelter')
    for shelter in Shelter.objects.all():
        shelter.capacity = random.choice(list(range(50, 1000)))
        shelter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0004_shelter_capacity'),
    ]

    operations = [
        migrations.RunPython(set_random_capacity)
    ]
