# Generated by Django 2.1.3 on 2018-11-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0005_auto_20181106_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationhistory',
            name='is_demo',
            field=models.BooleanField(default=True, verbose_name='デモ用'),
        ),
    ]
